# -*- coding: utf-8 -*-
"""Simple_machine_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5kN6Q5OH3_GmqT4Lpzn0NN7iKBthqqz
"""

#A simple machine learning model


#dependecies

from  sklearn.linear_model import LinearRegression
import random

feature_set=[]
answer_set=[]

#dataset creation

for i in range(0,200):
  x=random.randint(0,2000)
  y=random.randint(0,2000)
  z=random.randint(0,2000)

  function=(x*2)+(y*3)+(z*4)

  feature_set.append([x,y,z])
  answer_set.append(function)

#model train

model= LinearRegression()
model.fit(feature_set,answer_set)

test_set=[[8,9,5]]
prediction=model.predict(test_set)
print(prediction,model.coef_)